class Exception
{
    func what() String
    {
        return "An exception occured."
    }
}

try {
    throw "An exception occured."
} catch (e String) {
    print(e)
} finally {
    print("Execute finally.")
}

try {
    throw Exception()
} catch (e Exception) {
    print(e.what())
} catch {
    print("An exception occured.")
}
